"""The Maestro flow emitter — v2 codegen pillar 1 (a RUNNABLE artifact from the graph).

Mirrors the ENGINE's own command derivation (launch_anchor + flow_from_recording), so what
Maestro executes is what replay executes — the same skips (launcher-return gestures), the
same launch semantics, and chrome-fork scroll edges bridged with `scrollUntilVisible`
targeting the NEXT step's selector (the closest Maestro analog of the per-step reveal rung).

CODEGEN CONTRACT CLASS (`emits_selector_values=True`): selector values are the product and
DO appear — but the hard lines hold for every emitter class:
  * a sensitive field appears only as `inputText: ${param}` (run with
    `maestro test -e param=...`); a literal NEVER exists in the graph to begin with;
  * raw coordinates are NEVER transcribed — a coordinate-only step emits an explicit
    `# wendle:refused` comment (a flow that silently dropped a step would replay "green"
    while skipping a recorded interaction — the confident-wrong shape);
  * set_checked is REFUSED with a comment: Maestro has no idempotent state-set, and a
    blind tapOn inverts the state when it already matches (the §checkable rule).

Selector mapping (grounded on docs.maestro.dev): label union -> `tapOn: "<text>"` shorthand
(Maestro's text matcher is its own closest union analog); content_desc -> `description:`;
resource_id / hint-bound fields -> `id:`; long_click -> `longPressOn`; keyevent 4 -> `back`,
3 -> `pressKey: Home`."""
from __future__ import annotations

from wendle.emit.base import register
from wendle.graph import Graph
from wendle.replay.commands import flow_from_recording, launch_anchor


def _q(value) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _selector_lines(verb: str, sel) -> list:
    """Maestro selector block for a tap-class verb, or None for unrunnable kinds."""
    if sel.kind == "label":
        return [f"- {verb}: {_q(sel.value)}"]
    if sel.kind == "text":
        return [f"- {verb}:", f"    text: {_q(sel.value)}"]
    if sel.kind == "content_desc":
        return [f"- {verb}:", f"    description: {_q(sel.value)}"]
    if sel.kind in ("resource_id", "hint"):
        key = "id" if sel.kind == "resource_id" else "hintText"
        return [f"- {verb}:", f"    {key}: {_q(sel.value)}"]
    return None


def _scroll_target(sel) -> list:
    if sel.kind in ("label", "text"):
        return ["    element:", f"      text: {_q(sel.value)}"]
    if sel.kind == "content_desc":
        return ["    element:", f"      description: {_q(sel.value)}"]
    if sel.kind == "resource_id":
        return ["    element:", f"      id: {_q(sel.value)}"]
    return None


class MaestroEmitter:
    name = "maestro"
    emits_selector_values = True  # codegen class: values are the product (hard lines still hold)

    def emit(self, graph: Graph, recording_path=None) -> str:
        anchor = launch_anchor(graph)
        start_id = anchor.verified_fp if anchor is not None else None
        start = graph.screen(start_id) if start_id else None
        cmds = flow_from_recording(graph, start_id=start_id)
        app_id = start.package if start is not None and start.package else ""
        lines = [f"appId: {app_id}",
                 "# generated by wendle (wendle render --target maestro)",
                 "# sensitive fields are ${param} placeholders: maestro test -e param=...",
                 "---",
                 "- launchApp"]
        # a skipped chrome-fork scroll edge bridges via scrollUntilVisible on the NEXT selector
        ordered = list(graph.ordered_transitions())
        pending_scroll = False
        cmd_edges = {id(c): ordered[c.edge_index] for c in cmds if c.edge_index < len(ordered)}
        emitted_edges = {c.edge_index for c in cmds}
        scroll_edges = {i for i, (_u, _v, _k, d) in enumerate(ordered)
                        if d.get("action_class") == "scroll"}

        def flush_scroll(sel) -> None:
            nonlocal pending_scroll
            if not pending_scroll:
                return
            tgt = _scroll_target(sel) if sel is not None else None
            if tgt is not None:
                lines.append("- scrollUntilVisible:")
                lines.extend(tgt)
                lines.append("    direction: DOWN")
            else:
                lines.append("- scroll")
            pending_scroll = False

        prev_idx = -1
        for cmd in cmds:
            # any scroll edge between the previous emitted command and this one?
            if any(i in scroll_edges for i in range(prev_idx + 1, cmd.edge_index)):
                pending_scroll = True
            prev_idx = cmd.edge_index
            if cmd.kind == "launch":
                flush_scroll(None)
                pkg = cmd.anchor.value.split("/")[0] if cmd.anchor.value else ""
                lines.append("- launchApp:")
                lines.append(f"    appId: {_q(pkg)}")
                continue
            a = cmd.action
            if a.action_type == "set_text":
                flush_scroll(a.selector)
                param = (a.value or {}).get("param")
                field = _selector_lines("tapOn", a.selector)
                if field is None or (param is None and "text" not in (a.value or {})):
                    lines.append(f"# wendle:refused set_text without a runnable handle "
                                 f"(kind={a.selector.kind})")
                    continue
                lines.extend(field)
                if param is not None:
                    lines.append(f"- inputText: ${{{param}}}")
                else:
                    lines.append(f"- inputText: {_q((a.value or {}).get('text', ''))}")
                continue
            if a.action_type == "set_checked":
                # no idempotent state-set in Maestro; a blind tap inverts an already-correct
                # state — refuse explicitly (kind only, never the recorded state direction
                # presented as a command)
                lines.append(f"# wendle:refused set_checked ({a.selector.kind}) — Maestro has no "
                             f"idempotent state-set; verify manually")
                continue
            if a.action_type == "keyevent":
                flush_scroll(None)
                code = str(a.selector.value or (a.value or {}).get("code", ""))
                if code == "4":
                    lines.append("- back")
                elif code == "3":
                    lines.append("- pressKey: Home")
                else:
                    lines.append(f"# wendle:refused keyevent {code} (no Maestro analog)")
                continue
            verb = "longPressOn" if a.action_type == "long_click" else "tapOn"
            block = _selector_lines(verb, a.selector)
            if block is None:
                # coordinate-only (or otherwise unrunnable): explicit refusal — NEVER pixels,
                # never a silent drop that would let the flow pass while skipping a step
                lines.append(f"# wendle:refused coordinate-only step (no stable selector "
                             f"recorded; action={a.action_type})")
                pending_scroll = False
                continue
            flush_scroll(a.selector)
            lines.extend(block)
        return "\n".join(lines) + "\n"


register(MaestroEmitter())
